
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;
	private global::Gtk.Label label1;
	private global::Gtk.Label lNombre;
	private global::Gtk.Label lCodigo;
	private global::Gtk.Entry eNombre;
	private global::Gtk.Label lGrupo;
	private global::Gtk.Label lPregunta1;
	private global::Gtk.RadioButton radiobutton1;
	private global::Gtk.RadioButton radiobutton2;
	private global::Gtk.RadioButton radiobutton3;
	private global::Gtk.RadioButton radiobutton4;
	private global::Gtk.Label lPregunta2;
	private global::Gtk.ComboBox combobox1;
	private global::Gtk.SpinButton spinbutton1;
	private global::Gtk.CheckButton checkOpc1;
	private global::Gtk.CheckButton checkOpc2;
	private global::Gtk.CheckButton checkOpc3;
	private global::Gtk.CheckButton checkOpc4;
	private global::Gtk.Label lPregunta4;
	private global::Gtk.Label lPregunta3;
	private global::Gtk.Calendar calendar1;
	private global::Gtk.Button botonTerminar;
	private global::Gtk.Entry eCodigo;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Practica 7");
		this.fixed1.Add (this.label1);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label1]));
		w1.X = 247;
		w1.Y = 28;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lNombre = new global::Gtk.Label ();
		this.lNombre.Name = "lNombre";
		this.lNombre.LabelProp = global::Mono.Unix.Catalog.GetString ("Nombre");
		this.fixed1.Add (this.lNombre);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.lNombre]));
		w2.X = 43;
		w2.Y = 87;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lCodigo = new global::Gtk.Label ();
		this.lCodigo.Name = "lCodigo";
		this.lCodigo.LabelProp = global::Mono.Unix.Catalog.GetString ("Código");
		this.fixed1.Add (this.lCodigo);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.lCodigo]));
		w3.X = 51;
		w3.Y = 111;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.eNombre = new global::Gtk.Entry ();
		this.eNombre.CanFocus = true;
		this.eNombre.Name = "eNombre";
		this.eNombre.IsEditable = true;
		this.eNombre.InvisibleChar = '•';
		this.fixed1.Add (this.eNombre);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.eNombre]));
		w4.X = 126;
		w4.Y = 84;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lGrupo = new global::Gtk.Label ();
		this.lGrupo.Name = "lGrupo";
		this.lGrupo.LabelProp = global::Mono.Unix.Catalog.GetString ("Grupo");
		this.fixed1.Add (this.lGrupo);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.lGrupo]));
		w5.X = 342;
		w5.Y = 76;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lPregunta1 = new global::Gtk.Label ();
		this.lPregunta1.Name = "lPregunta1";
		this.lPregunta1.LabelProp = global::Mono.Unix.Catalog.GetString ("1.-Cúal es mi nombre?");
		this.fixed1.Add (this.lPregunta1);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.lPregunta1]));
		w6.X = 36;
		w6.Y = 174;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.radiobutton1 = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Joshua"));
		this.radiobutton1.CanFocus = true;
		this.radiobutton1.Name = "radiobutton1";
		this.radiobutton1.DrawIndicator = true;
		this.radiobutton1.UseUnderline = true;
		this.radiobutton1.Group = new global::GLib.SList (global::System.IntPtr.Zero);
		this.fixed1.Add (this.radiobutton1);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.radiobutton1]));
		w7.X = 40;
		w7.Y = 200;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.radiobutton2 = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Marco"));
		this.radiobutton2.CanFocus = true;
		this.radiobutton2.Name = "radiobutton2";
		this.radiobutton2.DrawIndicator = true;
		this.radiobutton2.UseUnderline = true;
		this.radiobutton2.Group = this.radiobutton1.Group;
		this.fixed1.Add (this.radiobutton2);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.radiobutton2]));
		w8.X = 151;
		w8.Y = 199;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.radiobutton3 = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Mariano"));
		this.radiobutton3.CanFocus = true;
		this.radiobutton3.Name = "radiobutton3";
		this.radiobutton3.DrawIndicator = true;
		this.radiobutton3.UseUnderline = true;
		this.radiobutton3.Group = this.radiobutton1.Group;
		this.fixed1.Add (this.radiobutton3);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.radiobutton3]));
		w9.X = 251;
		w9.Y = 197;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.radiobutton4 = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Pepe"));
		this.radiobutton4.CanFocus = true;
		this.radiobutton4.Name = "radiobutton4";
		this.radiobutton4.DrawIndicator = true;
		this.radiobutton4.UseUnderline = true;
		this.radiobutton4.Group = this.radiobutton1.Group;
		this.fixed1.Add (this.radiobutton4);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.radiobutton4]));
		w10.X = 374;
		w10.Y = 198;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lPregunta2 = new global::Gtk.Label ();
		this.lPregunta2.Name = "lPregunta2";
		this.lPregunta2.LabelProp = global::Mono.Unix.Catalog.GetString ("2.-Cuanto es 2 + 2?");
		this.fixed1.Add (this.lPregunta2);
		global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.lPregunta2]));
		w11.X = 44;
		w11.Y = 253;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.combobox1 = global::Gtk.ComboBox.NewText ();
		this.combobox1.AppendText (global::Mono.Unix.Catalog.GetString ("A"));
		this.combobox1.AppendText (global::Mono.Unix.Catalog.GetString ("B"));
		this.combobox1.AppendText (global::Mono.Unix.Catalog.GetString ("C"));
		this.combobox1.AppendText (global::Mono.Unix.Catalog.GetString ("D"));
		this.combobox1.AppendText (global::Mono.Unix.Catalog.GetString ("E"));
		this.combobox1.Name = "combobox1";
		this.combobox1.Active = 0;
		this.fixed1.Add (this.combobox1);
		global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.combobox1]));
		w12.X = 406;
		w12.Y = 71;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.spinbutton1 = new global::Gtk.SpinButton (0, 100, 1);
		this.spinbutton1.CanFocus = true;
		this.spinbutton1.Name = "spinbutton1";
		this.spinbutton1.Adjustment.PageIncrement = 10;
		this.spinbutton1.ClimbRate = 1;
		this.spinbutton1.Numeric = true;
		this.fixed1.Add (this.spinbutton1);
		global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.spinbutton1]));
		w13.X = 61;
		w13.Y = 288;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.checkOpc1 = new global::Gtk.CheckButton ();
		this.checkOpc1.CanFocus = true;
		this.checkOpc1.Name = "checkOpc1";
		this.checkOpc1.Label = global::Mono.Unix.Catalog.GetString ("México");
		this.checkOpc1.DrawIndicator = true;
		this.checkOpc1.UseUnderline = true;
		this.fixed1.Add (this.checkOpc1);
		global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.checkOpc1]));
		w14.X = 42;
		w14.Y = 378;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.checkOpc2 = new global::Gtk.CheckButton ();
		this.checkOpc2.CanFocus = true;
		this.checkOpc2.Name = "checkOpc2";
		this.checkOpc2.Label = global::Mono.Unix.Catalog.GetString ("España");
		this.checkOpc2.DrawIndicator = true;
		this.checkOpc2.UseUnderline = true;
		this.fixed1.Add (this.checkOpc2);
		global::Gtk.Fixed.FixedChild w15 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.checkOpc2]));
		w15.X = 154;
		w15.Y = 376;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.checkOpc3 = new global::Gtk.CheckButton ();
		this.checkOpc3.CanFocus = true;
		this.checkOpc3.Name = "checkOpc3";
		this.checkOpc3.Label = global::Mono.Unix.Catalog.GetString ("Japón");
		this.checkOpc3.DrawIndicator = true;
		this.checkOpc3.UseUnderline = true;
		this.fixed1.Add (this.checkOpc3);
		global::Gtk.Fixed.FixedChild w16 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.checkOpc3]));
		w16.X = 248;
		w16.Y = 373;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.checkOpc4 = new global::Gtk.CheckButton ();
		this.checkOpc4.CanFocus = true;
		this.checkOpc4.Name = "checkOpc4";
		this.checkOpc4.Label = global::Mono.Unix.Catalog.GetString ("Chile");
		this.checkOpc4.DrawIndicator = true;
		this.checkOpc4.UseUnderline = true;
		this.fixed1.Add (this.checkOpc4);
		global::Gtk.Fixed.FixedChild w17 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.checkOpc4]));
		w17.X = 338;
		w17.Y = 375;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lPregunta4 = new global::Gtk.Label ();
		this.lPregunta4.Name = "lPregunta4";
		this.lPregunta4.LabelProp = global::Mono.Unix.Catalog.GetString ("4.-Indique la fecha de la independencia de México");
		this.fixed1.Add (this.lPregunta4);
		global::Gtk.Fixed.FixedChild w18 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.lPregunta4]));
		w18.X = 46;
		w18.Y = 435;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lPregunta3 = new global::Gtk.Label ();
		this.lPregunta3.Name = "lPregunta3";
		this.lPregunta3.LabelProp = global::Mono.Unix.Catalog.GetString ("3.-De los siguientes paises, cuales son de America?");
		this.fixed1.Add (this.lPregunta3);
		global::Gtk.Fixed.FixedChild w19 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.lPregunta3]));
		w19.X = 42;
		w19.Y = 340;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.calendar1 = new global::Gtk.Calendar ();
		this.calendar1.CanFocus = true;
		this.calendar1.Name = "calendar1";
		this.calendar1.DisplayOptions = ((global::Gtk.CalendarDisplayOptions)(35));
		this.fixed1.Add (this.calendar1);
		global::Gtk.Fixed.FixedChild w20 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.calendar1]));
		w20.X = 49;
		w20.Y = 487;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.botonTerminar = new global::Gtk.Button ();
		this.botonTerminar.CanFocus = true;
		this.botonTerminar.Name = "botonTerminar";
		this.botonTerminar.UseUnderline = true;
		this.botonTerminar.Label = global::Mono.Unix.Catalog.GetString ("Terminar");
		this.fixed1.Add (this.botonTerminar);
		global::Gtk.Fixed.FixedChild w21 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.botonTerminar]));
		w21.X = 337;
		w21.Y = 673;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.eCodigo = new global::Gtk.Entry ();
		this.eCodigo.CanFocus = true;
		this.eCodigo.Name = "eCodigo";
		this.eCodigo.IsEditable = true;
		this.eCodigo.InvisibleChar = '•';
		this.fixed1.Add (this.eCodigo);
		global::Gtk.Fixed.FixedChild w22 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.eCodigo]));
		w22.X = 126;
		w22.Y = 122;
		this.Add (this.fixed1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 637;
		this.DefaultHeight = 751;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
	}
}
